export const VERSION = '1.3.0'
export * from './types'
export {MetahubError, MetahubErrorCode} from './errors'
export {Emitter} from './events'
export type {EventMap} from './events'
export {discoverProvider} from './provider'
export type {MetahubProvider, DiscoverOptions} from './provider'
export {MetahubClient} from './client'
export type {MetahubClientOptions, ConnectResult} from './client'
